### PR TITLE
Function name update in TcpListener

### PR DESCRIPTION
**Pull request by Limerio**
For every examples the keyword **new** in TcpListener are here but in the lastest version they doesn't exist and i think it's the same for the testing env

### CODE REVIEW

**Comment by Limerio** [comment]
(the last fix is for the rest of the examples outside the github web UI)

**Comment by chrislearn** [comment]
The main branch is latest code and not ready for release, this version will release as soon as hyper 1.0 released.

```rust
TcpListener::new("127.0.0.1:7878").bind().await
```
This is latest and not released.

**Comment by Limerio** [comment]
My bad sorry

**Comment by chrislearn** [comment]
👌

**Pull request closed without merging**
