### PR TITLE
Fix #754

### LINKED ISSUE #754: Salvo does not take into account the schema name for generics
Hello,

I've noticed that when using generics, salvo doesn't take the schema name into account but gives the full path name of the struct.

let's take the example of these two structures : 

```rust
use std::fmt::Debug;
use salvo::oapi::ToSchema;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug, ToSchema)]
#[salvo(schema(symbol = "City"))]
pub struct CityDTO {
    #[salvo(schema(rename = "id"))]
    pub id: String,
    #[salvo(schema(rename = "name"))]
    pub name: String,
}

#[derive(Serialize, Deserialize, Debug, ToSchema)]
#[salvo(schema(symbol = "Response"))]
pub struct ApiResponse<T: Serialize + ToSchema + Send + Debug + 'static> {
    // + Send + 'static
    #[salvo(schema(rename = "status"))]
    /// status code
    pub status: String,
    #[salvo(schema(rename = "msg"))]
    /// Status msg
    pub message: String,
    #[salvo(schema(rename = "data"))]
    /// The data returned
    pub data: T,
}

```

and this is the simplified Rest controller : 

```rust
#[endpoint(operation_id = "get_all_cities", tags("city"), status_codes(200, 400, 401, 403, 500))]
pub async fn get_all_cities() -> Result<Json<ApiResponse<Vec<CityDTO>>>, StatusError> {
    match services::city_service::get_all_cities().await {
        Ok(entities) => Ok(Json(ApiResponse::new(
            "200",
            "OK",
            CityMapper::entities_to_dtos(&entities),
        ))),
        Err(_) => Err(StatusError::internal_server_error()),
    }
}

```

here's the result swagger : 

Screenshot from 2024-04-17 12-39-03

generic names are no good : 

```
Response<alloc::string::String>
Response<alloc::vec::Vec<test_api::dtos::city_dto::CityDTO>>
salvo_core.http.errors.status_error.StatusError
```

normally it would be : 

```
Response<String>
Response<City>>
salvo_core.http.errors.status_error.StatusError // <!--------- it must not appear
```

thanks in advance

### PR DESCRIPTION
**Pull request by zhangkai803**

### CODE REVIEW

**Comment by zhangkai803** [comment]
Here is the doc of `example-oapi-generics` before this PR:
image

now:
image

**Comment by zhangkai803** [comment]
Here is the doc of `example-oapi-todos` before this PR:
image

now:

**Comment by zhangkai803** [comment]
And `$ref` reference to the real location of the structs now.
```rust
#[derive(Serialize, Deserialize, Clone, Debug, ToSchema)]
#[salvo(schema(symbol = "City"))]
pub(crate) struct CityDTO {
    #[salvo(schema(rename = "id"))]
    pub(crate) id: String,
    #[salvo(schema(rename = "name"))]
    pub(crate) name: String,
}
```
image

**Comment by chrislearn** [comment]
这个等我有空了，再考虑如何改进，可能要晚些合并了。
主要感觉是三个问题：
1. 泛型的问题，openapi 不支持<>.
2. 重命名类型为短名称，以及是否应该有一个批量重命名的方法？如果名称出现冲突如何解决？
3. 如果可能 ，是否应该结合其他验证库，读取里面的验证信息，转为 openapi 里面支持的验证信息。

**Comment by zhangkai803** [comment]
> 这个等我有空了，再考虑如何改进，可能要晚些合并了。 主要感觉是三个问题：
> 
> 1. 泛型的问题，openapi 不支持<>.
> 2. 重命名类型为短名称，以及是否应该有一个批量重命名的方法？如果名称出现冲突如何解决？
> 3. 如果可能 ，是否应该结合其他验证库，读取里面的验证信息，转为 openapi 里面支持的验证信息。

没问题

**Comment by rxdiscovery** [comment]
> And `$ref` reference to the real location of the structs now.
> 
> ```rust
> #[derive(Serialize, Deserialize, Clone, Debug, ToSchema)]
> #[salvo(schema(symbol = "City"))]
> pub(crate) struct CityDTO {
>     #[salvo(schema(rename = "id"))]
>     pub(crate) id: String,
>     #[salvo(schema(rename = "name"))]
>     pub(crate) name: String,
> }
> ```
> 
> image


I think it's better to leave $ref = "#/components/schemas/City", to prevent displaying the internal structure of the source code. and that's what all OAPI generation frameworks do.

**Comment by zhangkai803** [comment]
> > And `$ref` reference to the real location of the structs now.
> > ```rust
> > #[derive(Serialize, Deserialize, Clone, Debug, ToSchema)]
> > #[salvo(schema(symbol = "City"))]
> > pub(crate) struct CityDTO {
> >     #[salvo(schema(rename = "id"))]
> >     pub(crate) id: String,
> >     #[salvo(schema(rename = "name"))]
> >     pub(crate) name: String,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > image
> 
> @zhangkai803 I think it's better to leave` $ref = "#/components/schemas/City"`, to prevent displaying the internal structure of the source code. and that's what all OAPI generation frameworks do.

Thanks. It's a good point. I'll take this into account.

**Comment by chrislearn** [comment]
https://github.com/salvo-rs/salvo/blob/main/crates/oapi/src/naming.rs

我给了一种可以全局修改命名方式的PR。可以根据自己的喜好重命名类型。

**Comment by zhangkai803** [comment]
This PR was not longer needed. Please check out the main branch.

**Pull request closed without merging**
